### ISSUE TITLE
DONUTS for binary traits

### ISSUE THREAD

**Issue by tom-a-bond** [qlu-lab/DONUTS#1]
Hi, could you advise whether DONUTS is valid for binary outcomes analysed using logistic regression please?

**Comment by yuchang-wu** [comment]
Hi,

Thanks for the question!

We did not extensively examine DONUTS' performance on binary traits, but we believe _in general_ the beta (i.e., logOR) from the logistic regressions can be used as DONUTS inputs since 

1. people usually assume an underlying continuous liability for a binary trait (i.e., liability threshold model) and the effect sizes in the liability scale can certainly be used by DONUTS 
2. when the variance in liability "explained" by a SNP is not too large (empirically < 6%), there's a linear approximation between the effect size in logit scale (i.e., logOR) and the effect size in liability scale; and this linear relationship depends only on the disease prevalence. See [Wu and Sham (2021)](https://link.springer.com/article/10.1007/s10519-021-10042-2) for the transformation in effect sizes between liability and logit scales.

Feel free to let me know if anything's not clear. 

Thank you!
Yuchang Wu

**Comment by tom-a-bond** [comment]
That is helpful, much appreciated!
